services:
  # Source PostgreSQL (ShopEase)
  postgres_source:
    image: postgres:15
    container_name: shopease_postgres
    environment:
      POSTGRES_DB: shopease_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shopease123
    ports:
      - "5433:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ../data/raw:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Airflow metadata database
  postgres_airflow:
    image: postgres:13
    container_name: airflow_metadata_db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ../data/airflow_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  # Airflow webserver
  airflow-webserver:
    build: .
    image: airflow-retail:latest
    container_name: airflow_webserver
    depends_on:
      postgres_airflow:
        condition: service_healthy
      postgres_source:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"

  # Airflow scheduler
  airflow-scheduler:
    build: .
    image: airflow-retail:latest
    container_name: airflow_scheduler
    depends_on:
      postgres_airflow:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../logs:/opt/airflow/logs
    command: airflow scheduler
